services:
  mysql:
    image: 7dcddc01f13b
    container_name: mysql-my-game-user
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql